server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8      
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  devtools:
    livereload:
      enabled: true
  datasource:
      url: jdbc:oracle:thin:@192.168.0.50:1521/PDSYS
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: TS_USER
      password: TS_USER
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true


